# Generated by Django 4.2.9 on 2026-09-06 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('capacity', models.FloatField(default=0.0, help_text='Total capacity in kWh')),
                ('stored_energy', models.FloatField(default=0.0, help_text='Currently stored energy in kWh')),
                ('battery_level', models.FloatField(default=0.0, help_text='Battery level 0–100 %')),
                ('voltage', models.FloatField(default=0.0, help_text='Voltage in V')),
                ('current', models.FloatField(default=0.0, help_text='Current in A')),
                ('temperature', models.FloatField(default=0.0, help_text='Temperature in °C')),
                ('health', models.FloatField(default=100.0, help_text='Battery health 0–100 %')),
                ('status', models.CharField(choices=[('Charging', 'Charging'), ('Discharging', 'Discharging'), ('Full', 'Full'), ('Idle', 'Idle'), ('Fault', 'Fault')], db_index=True, default='Idle', max_length=20)),
                ('charging_power', models.FloatField(default=0.0, help_text='Charging power in kW')),
                ('energy_received_today', models.FloatField(default=0.0, help_text='kWh received today')),
                ('energy_supplied_today', models.FloatField(default=0.0, help_text='kWh supplied today')),
                ('charge_cycles', models.PositiveIntegerField(default=0)),
                ('last_full_charge', models.DateTimeField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Battery',
                'verbose_name_plural': 'Batteries',
                'ordering': ['battery_id'],
            },
        ),
        migrations.CreateModel(
            name='BatteryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_level', models.FloatField(help_text='Battery level % at this point in time')),
                ('temperature', models.FloatField(help_text='Temperature °C at this point in time')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('battery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='battery.battery')),
            ],
            options={
                'verbose_name': 'Battery History Record',
                'verbose_name_plural': 'Battery History',
                'ordering': ['-timestamp'],
            },
        ),
    ]
