# Generated by Django 4.2.9 on 2026-09-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnvironmentalStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_energy_generated', models.FloatField(default=0.0, help_text='Total renewable energy generated in kWh')),
                ('co2_saved', models.FloatField(default=0.0, help_text='CO2 avoided in kg')),
                ('cost_saved', models.FloatField(default=0.0, help_text='Cost saved in local currency')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Environmental Stats',
                'verbose_name_plural': 'Environmental Stats',
                'ordering': ['-date'],
            },
        ),
    ]
