# Generated by Django 4.2.9 on 2026-09-06 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StreetLight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('location', models.CharField(db_index=True, max_length=100)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Non-Working', 'Non-Working'), ('Fault', 'Fault'), ('Offline', 'Offline')], db_index=True, default='Working', max_length=20)),
                ('state', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], db_index=True, default='OFF', max_length=5)),
                ('power', models.FloatField(default=0.0, help_text='Power consumption in W')),
                ('voltage', models.FloatField(default=0.0, help_text='Voltage in V')),
                ('fault', models.CharField(blank=True, default='None', max_length=100)),
                ('communication_status', models.CharField(choices=[('Connected', 'Connected'), ('Disconnected', 'Disconnected'), ('Weak Signal', 'Weak Signal')], default='Connected', max_length=20)),
                ('brightness', models.FloatField(default=100.0, help_text='Brightness 0–100 %')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Street Light',
                'verbose_name_plural': 'Street Lights',
                'ordering': ['light_id'],
            },
        ),
        migrations.CreateModel(
            name='StreetLightHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=5)),
                ('power', models.FloatField(default=0.0, help_text='Power in W at this point in time')),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('street_light', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='streetlights.streetlight')),
            ],
            options={
                'verbose_name': 'Street Light History Record',
                'verbose_name_plural': 'Street Light History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_type', models.CharField(choices=[('LED Failure', 'LED Failure'), ('Power Failure', 'Power Failure'), ('Communication Failure', 'Communication Failure'), ('Voltage Issue', 'Voltage Issue'), ('Other', 'Other')], db_index=True, max_length=30)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('Warning', 'Warning'), ('Info', 'Info')], db_index=True, max_length=10)),
                ('message', models.TextField(blank=True, default='')),
                ('resolved', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('street_light', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faults', to='streetlights.streetlight')),
            ],
            options={
                'verbose_name': 'Fault',
                'verbose_name_plural': 'Faults',
                'ordering': ['-created_at'],
            },
        ),
    ]
