# Generated by Django 4.2.9 on 2026-09-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Solar', 'Solar'), ('Footstep', 'Footstep')], db_index=True, max_length=20, unique=True)),
                ('power_output', models.FloatField(default=0.0, help_text='Current power output in kW')),
                ('energy_today', models.FloatField(default=0.0, help_text='Energy generated today in kWh')),
                ('energy_week', models.FloatField(default=0.0, help_text='Energy generated this week in kWh')),
                ('energy_month', models.FloatField(default=0.0, help_text='Energy generated this month in kWh')),
                ('efficiency', models.FloatField(default=0.0, help_text='Efficiency percentage 0–100')),
                ('peak_power', models.FloatField(default=0.0, help_text='Peak power recorded today in kW')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Energy Source',
                'verbose_name_plural': 'Energy Sources',
                'ordering': ['source'],
            },
        ),
        migrations.CreateModel(
            name='EnergyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Solar', 'Solar'), ('Footstep', 'Footstep'), ('Total', 'Total')], db_index=True, max_length=20)),
                ('energy', models.FloatField(default=0.0, help_text='Energy in kWh')),
                ('date', models.DateField(db_index=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Energy History Record',
                'verbose_name_plural': 'Energy History',
                'ordering': ['-date', 'source'],
                'unique_together': {('source', 'date')},
            },
        ),
    ]
